apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: production
type: Opaque
data:
  SECRET_KEY: YWRtaW4=
  SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: Z29vZ2xlLWF1dGgta2V5
  SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: Z29vZ2xlLWF1dGgtc2VjcmV0
  STRIPE_PUBLIC_KEY: c3RyaXBlLXB1YmxpYy1rZXk=
  STRIPE_SECRET_KEY: c3RyaXBlLXNlY3JldC1rZXk=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ostad-module-six-pod
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ostad-module-six
  template:
    metadata:
      labels:
        app: ostad-module-six
    spec:
      containers:
        - name: ostad-module-six-container
          image: showrav13/ostad-mod-six:v3
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: ostad-module-six-service
  namespace: production
spec:
  type: NodePort
  selector:
    app: ostad-module-six
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30009